[package]
name = "modern_compiler_architecture"
version = "0.1.0"
edition = "2024"

[dependencies]
inc-complete = "0.4.1"
serde = { version = "1.0", features = ["derive", "rc"] }
ron = "0.10.1"
deterministic-hash = "1.0.1"
