[package]
name = "modern_compiler_architecture"
version = "0.1.0"
edition = "2024"

[dependencies]
inc-complete = { path = "../inc-complete" }
serde = { version = "1.0", features = ["derive", "rc"] }
ron = "0.10.1"
deterministic-hash = "1.0.1"
rayon = "1.10.0"
scc = "2.3.4"
