[package]
name = "modern_compiler_architecture"
version = "0.1.0"
edition = "2024"

[dependencies]
inc-complete = { version = "0.3.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
